version: '3'
services:
  app:
    build: productsApp
    restart: always
    volumes:
      - ./productsApp:/root
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo:3.4-xenial
    restart: always
    volumes:
      - ./productsApp/db/data:/data/db
    ports:
      - "27017:27017"