version: '3'

services:
  phoenix:
    build: phx_project
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./phx_project:/app
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
  redis:
    image: redis:6
    restart: always
    ports:
      - 6379:6379
    command: redis-server