version: '3'

services:
  phoenix:
    build: phx_project
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - redis
      - elasticsearch
      - rabbitmq
    volumes:
      - ./phx_project:/app
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
  redis:
    image: redis:6
    restart: always
    ports:
      - 6379:6379
    command: redis-server
  elasticsearch:
    image: elasticsearch:7.11.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.11.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  rabbitmq:
    image: rabbitmq:3.6.16-management
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
  email_service:
    build: email_service
    ports:
      - 5000:4000
    depends_on:
      - rabbitmq
    volumes:
      - ./email_service:/app

volumes:
  esdata:
    driver: local
